export const types = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',

  SET_EMAIL_DATA: 'SET_EMAIL_DATA',
  SET_SOCIAL_EMAIL_DATA: 'SET_SOCIAL_EMAIL_DATA',
  SET_LOCATION_DATA: 'SET_LOCATION_DATA',
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_PROFILE_DATA: 'SET_PROFILE_DATA',
  SET_SOCIAL_MEDIA_DATA: 'SET_SOCIAL_MEDIA_DATA',

  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  LOG_IN_USER_REQUEST: 'LOG_IN_USER_REQUEST',
  LOG_IN_USER_SUCCESS: 'LOG_IN_USER_SUCCESS',
  LOG_IN_USER_FAILURE: 'LOG_IN_USER_FAILURE',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  LOG_OUT_USER_REQUEST: 'LOG_OUT_USER_REQUEST',
  LOG_OUT_USER_SUCCESS: 'LOG_OUT_USER_SUCCESS',
  LOG_OUT_USER_FAILURE: 'LOG_OUT_USER_FAILURE',
};
