export const types = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',
  SET_EMAIL_DATA: 'SET_EMAIL_DATA',
  SET_SOCIAL_EMAIL_DATA: 'SET_SOCIAL_EMAIL_DATA',
  SET_LOCATION_DATA: 'SET_LOCATION_DATA',
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_PROFILE_DATA: 'SET_PROFILE_DATA',
  SET_SOCIAL_MEDIA_DATA: 'SET_SOCIAL_MEDIA_DATA',
};
