// eslint-disable-next-line import/prefer-default-export
export const types = {
  START_LOADING: 'START_LOADING',
  STOP_LOADING: 'STOP_LOADING',

  SET_EMAIL_DATA: 'SET_EMAIL_DATA',
  SET_SOCIAL_EMAIL_DATA: 'SET_SOCIAL_EMAIL_DATA',
  SET_LOCATION_DATA: 'SET_LOCATION_DATA',
  SET_USER_TYPE: 'SET_USER_TYPE',
  SET_PROFILE_DATA: 'SET_PROFILE_DATA',
  SET_SOCIAL_MEDIA_DATA: 'SET_SOCIAL_MEDIA_DATA',
  SET_USER_NAME: 'SET_USER_NAME',
  GET_ALL_JOBS: 'GET_ALL_JOBS',
  GET_ALL_MENTOR_TYPES: 'GET_ALL_MENTOR_TYPES',
  SET_USER_CHOISE: 'SET_USER_CHOISE',

  USER_INFO_REQUEST: 'USER_INFO_REQUEST',
  USER_INFO_SUCCESS: 'USER_INFO_SUCCESS',
  USER_INFO_FAIL: 'USER_INFO_FAIL',

  REGISTER_USER_REQUEST: 'REGISTER_USER_REQUEST',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  LOG_IN_USER_REQUEST: 'LOG_IN_USER_REQUEST',
  LOG_IN_USER_SUCCESS: 'LOG_IN_USER_SUCCESS',
  LOG_IN_USER_FAILURE: 'LOG_IN_USER_FAILURE',

  LOG_OUT_USER: 'LOG_OUT_USER',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',

  SAVE_TOKEN: 'SAVE_TOKEN'
};
