export const types = {
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_FAIL: 'FETCH_USER_FAIL',

  UPDATE_USER_PROFILE_REQUEST: 'UPDATE_USER_PROFILE_REQUEST',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILURE: 'UPDATE_USER_PROFILE_FAILURE',

  UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
  UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
  UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',

  UPLOAD_USER_IMAGE_REQUEST: 'UPLOAD_USER_IMAGE_',
  UPLOAD_USER_IMAGE_SUCCESS: 'UPLOAD_USER_IMAGE_SUCCESS',
  UPLOAD_USER_IMAGE_FAILURE: 'UPLOAD_USER_IMAGE_FAILURE',

  FETCH_ALL_USERS_REQUEST: 'FETCH_ALL_USERS_REQUEST',
  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILURE: 'FETCH_ALL_USERS_FAILURE',

  CHECK_USER_PROFILE_REQUEST: 'CHECK_USER_PROFILE_REQUEST',
  CHECK_USER_PROFILE_SUCCESS: 'CHECK_USER_PROFILE_SUCCESS',
  CHECK_USER_PROFILE_FAILURE: 'CHECK_USER_PROFILE_FAILURE',
};
